[build]
  base = "frontend"
  publish = "out"
  command = "next build && next start"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"
