[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"
